# Generated by Django 4.0.2 on 2022-03-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookaccino_auth', '0001_initial'),
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookaccino_auth.profile')),
            ],
        ),
    ]
