# Generated by Django 4.0.2 on 2022-03-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_quotes_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
