# Generated by Django 4.0.2 on 2022-03-18 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebook',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='profilebook',
            name='currently_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilebook',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilebook',
            name='want_to_read',
            field=models.BooleanField(default=False),
        ),
    ]
