# Generated by Django 4.0.2 on 2022-03-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_profilebook_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilebook',
            name='currently_reading',
        ),
        migrations.RemoveField(
            model_name='profilebook',
            name='read',
        ),
        migrations.RemoveField(
            model_name='profilebook',
            name='want_to_read',
        ),
    ]
