# Generated by Django 4.0.2 on 2022-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_profilebook_currently_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebook',
            name='book_state',
            field=models.CharField(choices=[('reading', 'Currently Reading'), ('read', 'Read'), ('want_to_read', 'Want to read'), ('not_reading', 'Not reading')], default='not_reading', max_length=30),
        ),
    ]
