# Generated by Django 4.0.2 on 2022-03-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookaccino_auth', '0002_alter_profile_books'),
        ('book', '0011_profilebook_book_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilebook',
            unique_together={('profile', 'book')},
        ),
    ]
