# Generated by Django 4.0.2 on 2022-03-24 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_quote_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilebook',
            old_name='created_date',
            new_name='added_date',
        ),
        migrations.AddField(
            model_name='book',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
