# Generated by Django 4.0.2 on 2022-03-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_rename_created_date_profilebook_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
