# Generated by Django 4.0.3 on 2022-03-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_profilebook_added_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
