# Generated by Django 4.0.3 on 2022-04-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_delete_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
