# Generated by Django 4.0.2 on 2022-03-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_profilebook'),
        ('bookaccino_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(blank=True, through='book.ProfileBook', to='book.Book'),
        ),
    ]
